Update gradle-run.yml

diff --git a/.github/workflows/gradle-run.yml b/.github/workflows/gradle-run.yml
--- a/.github/workflows/gradle-run.yml
+++ b/.github/workflows/gradle-run.yml
@@ -45,13 +45,23 @@ jobs:
       - name: Query BQ
         run: bq query --use_legacy_sql=false 'SELECT COUNT(*) FROM `muskan-dlp-test-local3.gh_test_2`.__TABLES__'
       
-      - name: Store results in variable
+      - name: Install BQ library
         run: |
-          export TABLE_COUNT=$(bq query --use_legacy_sql=false 'SELECT COUNT(*) FROM `muskan-dlp-test-local3.gh_test_2`.__TABLES__')
-          echo "The number of tables is $TABLE_COUNT"
+          bq_library=$(which bq)
+          if [[ -z $bq_library ]]; then
+            echo "Error: Could not find the bq command-line tool."
+            exit 1
+          fi
+          tables=$(bq ls)
+          for table in $tables; do
+            rows=$(bq show --format=tablerows $table | wc -l)
+            if [[ $rows -eq 0 ]]; then
+              echo "Table $table is empty."
+            fi
+          done
           
-      - name: Print RESULT
-        run: echo "The number of tables is $TABLE_COUNT"
+#       - name: Print RESULT
+#         run: echo "The number of tables is $TABLE_COUNT"
         
 #       - name: conditional
 #         run: |
